baseURL = "https://blog-omn8.onrender.com"
languageCode = "en-us"
title = "Ortexo Blog"
theme = "yeet"

[params]
github = "ortexo"
email = "Hello@ortexo.com"
url = "https://ortexo.com"
keywords = "Blog, saas, npocore, ortexo"

